# Licensed under the Apache License, Version 2.0 or the MIT License.
# SPDX-License-Identifier: Apache-2.0 OR MIT
# Copyright OXIDOS AUTOMOTIVE 2024.

name: Rust Build & Test

on:
  workflow_dispatch:
    inputs:
      defaultFeature:
        type: boolean
        description: 'Default feature'     
        required: true
        default: true
      tags:
        description: 'libudev-dev dependency'  
  push:
  pull_request:
  merge_group:

env:
  CARGO_TERM_COLOR: always
  DEFAULT_FEATURE: true

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Override defaultFeature from input (if workflow_dispatch)
      run: |
        if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
          echo "DEFAULT_FEATURE=${{ github.event.inputs.defaultFeature }}" >> $GITHUB_ENV
        fi
    - name: Install libudev
      run: |
        if [ $DEFAULT_FEATURE == true ]; then
          sudo apt-get install -y  libudev-dev
        else
          echo Skipped libudev install
        fi
    - name: Tauri dependencies
      run: |
          sudo apt update && sudo apt install -y \
            libwebkit2gtk-4.1-dev \
            build-essential \
            curl \
            wget \
            file \
            libxdo-dev \
            libssl-dev \
            libayatana-appindicator3-dev \
            librsvg2-dev \
            webkit2gtk-driver \
            xvfb
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

  ci-format:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        components: rustfmt
    - name: ci-job-format
      run:  make ci-job-format

  ci-clippy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1 
      with:
        toolchain: stable
        components: clippy
    - name: Install libudev
      run: |
        if [ $DEFAULT_FEATURE == true ]; then
          sudo apt-get install -y  libudev-dev
        else
          echo Skipped libudev install
        fi
    - name: Tauri dependencies
      run: |
          sudo apt update && sudo apt install -y \
            libwebkit2gtk-4.1-dev \
            build-essential \
            curl \
            wget \
            file \
            libxdo-dev \
            libssl-dev \
            libayatana-appindicator3-dev \
            librsvg2-dev \
            webkit2gtk-driver \
            xvfb
    - name: ci-job-clippy
      run:  make ci-job-clippy
